# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Identyfikator urządzenia')),
                ('setting', models.CharField(choices=[('ADDR', 'ADDR'), ('BTNAME', 'BTNAME'), ('DISPTIME', 'DISPTIME'), ('LOCATION', 'LOCATION'), ('PM10NORM', 'PM10NORM'), ('PRESSREF', 'PRESSREF'), ('READFREQ', 'READFREQ'), ('SAMPSIZE', 'SAMPSIZE')], max_length=30)),
                ('value', models.CharField(default=None, max_length=50)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
