# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatherer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WORKING', 'Przetwarzanie'), ('READY', 'Gotowe')], default='READY', max_length=10, verbose_name='Stan')),
                ('run_by', models.CharField(choices=[('UI', 'Interfejs'), ('CRON', 'Harmonogram')], default='CRON', max_length=10, verbose_name='Uruchomiony przez')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Czas uruchomienia')),
            ],
        ),
    ]
