# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('city', models.CharField(max_length=100, verbose_name='miasto')),
            ],
            options={
                'verbose_name_plural': 'obszary',
                'verbose_name': 'obszar',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='czas pomiaru')),
                ('value', models.FloatField(verbose_name='wartość')),
            ],
            options={
                'verbose_name_plural': 'pomiary',
                'verbose_name': 'pomiar',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('description', models.CharField(max_length=1024, verbose_name='opis')),
                ('norm', models.FloatField(verbose_name='norma godzinowa (µg)')),
            ],
            options={
                'verbose_name_plural': 'parametry',
                'verbose_name': 'parametr',
            },
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('street', models.CharField(max_length=100, verbose_name='ulica')),
                ('added', models.DateField(default=django.utils.timezone.now, verbose_name='data dodania')),
                ('url', models.URLField(verbose_name='adres zasobu')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='webui.Area')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='webui.Parser')),
            ],
            options={
                'verbose_name_plural': 'stacje',
                'verbose_name': 'stacja',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='webui.Station'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='webui.Parameter'),
        ),
    ]
