# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20170114_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='url',
            field=models.URLField(null=True, verbose_name='adres zasobu'),
        ),
    ]
