# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_auto_20180517_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.CharField(max_length=1024, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='norm',
            field=models.FloatField(null=True, verbose_name='norma godzinowa (µg)'),
        ),
    ]
