# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_auto_20180517_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(max_length=20, null=True, verbose_name='jednostka'),
        ),
    ]
