# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-22 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_parameter_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement15mAggr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='czas pomiaru')),
                ('value', models.FloatField(verbose_name='wartość')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.Station')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.Parameter')),
            ],
            options={
                'verbose_name': 'pomiar uśredniony',
                'verbose_name_plural': 'pomiary uśrednione',
            },
        ),
    ]
