# Generated by Django 2.0.6 on 2018-06-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_measurement15maggr'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement15maggr',
            name='date_s',
            field=models.DateField(default='0001-01-01', verbose_name='data pomiaru'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement15maggr',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Station'),
        ),
        migrations.AlterField(
            model_name='measurement15maggr',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webui.Parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='norm',
            field=models.FloatField(blank=True, null=True, verbose_name='norma godzinowa (µg)'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='jednostka'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='adres zasobu'),
        ),
        migrations.AddIndex(
            model_name='measurement15maggr',
            index=models.Index(fields=['date_s', 'type'], name='webui_measu_date_s_9e191e_idx'),
        ),
    ]
